"""Constants for the Perfectly Snug integration."""

DOMAIN = "perfectly_snug"
MANUFACTURER = "Perfectly Snug Inc."
MODEL = "Smart Topper"

CONF_LEFT_IP = "left_ip"
CONF_RIGHT_IP = "right_ip"
CONF_SINGLE_ZONE = "single_zone"
CONF_ROOM_TEMP_ENTITY = "room_temp_entity"

# WebSocket
WS_ENDPOINT = "/PSWS"
WS_ORIGIN = "capacitor://localhost"

# Protocol
MSG_GROUP_CTRL = 2
CTRL_CMD_SET_SETTING = 0
CTRL_CMD_GET_SETTINGS = 3
CTRL_MSG_SETTING = 2
CTRL_MSG_SETTINGS = 4

# Setting IDs
SETTING_L1 = 0
SETTING_L2 = 1
SETTING_L3 = 2
SETTING_FOOT_WARMER = 3
SETTING_QUIET_ENABLE = 4
SETTING_HEATER_LIMIT = 6
SETTING_VOLUME = 11
SETTING_T1 = 12
SETTING_T3 = 13
SETTING_SCHEDULE_ENABLE = 14
SETTING_RUNNING = 21
SETTING_RUN_PROGRESS = 23
SETTING_TEMP_SETPOINT = 30
SETTING_TEMP_AMBIENT = 31
SETTING_TEMP_SENSOR_RIGHT = 32
SETTING_TEMP_SENSOR_CENTER = 33
SETTING_TEMP_SENSOR_LEFT = 34
SETTING_BL_OUT = 39
SETTING_HH_OUT = 40
SETTING_FH_OUT = 41
SETTING_CTRL_OUT = 42
SETTING_CTRL_ITERM = 43
SETTING_CTRL_PTERM = 44
SETTING_PROFILE_ENABLE = 52
SETTING_COOLING_MODE = 53

# All settings we poll — only settings that an entity actually reads
POLL_SETTINGS = [
    SETTING_L1, SETTING_L2, SETTING_L3,
    SETTING_FOOT_WARMER, SETTING_QUIET_ENABLE,
    SETTING_HEATER_LIMIT, SETTING_VOLUME,
    SETTING_T1, SETTING_T3,
    SETTING_SCHEDULE_ENABLE,
    SETTING_RUNNING, SETTING_RUN_PROGRESS,
    SETTING_TEMP_SETPOINT, SETTING_TEMP_AMBIENT,
    SETTING_TEMP_SENSOR_RIGHT, SETTING_TEMP_SENSOR_CENTER, SETTING_TEMP_SENSOR_LEFT,
    SETTING_BL_OUT, SETTING_HH_OUT, SETTING_FH_OUT,
    SETTING_CTRL_OUT, SETTING_CTRL_ITERM, SETTING_CTRL_PTERM,
    SETTING_PROFILE_ENABLE, SETTING_COOLING_MODE,
]

# Temperature sensor setting IDs (confirmed accurate with (raw-32768)/100 formula)
TEMP_SETTINGS = {
    SETTING_TEMP_SETPOINT, SETTING_TEMP_AMBIENT,
    SETTING_TEMP_SENSOR_RIGHT, SETTING_TEMP_SENSOR_CENTER, SETTING_TEMP_SENSOR_LEFT,
}

PLATFORMS = ["sensor", "switch", "number"]

UPDATE_INTERVAL = 30  # seconds
